name = "Fabric Installer"
filename = "fabric-installer-0.11.1.jar"
side = "server"

[download]
url = "https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.11.1/fabric-installer-0.11.1.jar"
hash-format = "sha256"
hash = "7917f9fa14be6da6ef3cdb7fe6bf3b63a593a0eb873bd627e981a7e3988cd73a"
