name = "GLuaMC22"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "675068f797efdd5f42a82d9f0b24255342c8eaa5e4ea51628c2f421a8eab3fa1"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
