name = "GLuaMC22"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7373a75334fb725dcfe3671032a6b451777e412d8454d5f983b3cafcca6059b6"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
