name = "GLuaMC22"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdbcd45ef1d35459a4ed44217143871195922219fa8e1317166ce5d39ada87b8"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
