name = "GLuaMC22"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "276a4b37e68de4215119d5a2cca7223c26871edd8198454175ba0dc773a0f70d"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1", "1.18"]
