name = "Anarchocapitalism Simulator 2021"
author = "GLua"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f5f5a6b87a0f378890cfad190d00fabd965c0c0b971f81f2969462d362c9f7f"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
