name = "Anarchocapitalism Simulator 2021"
author = "GLua"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23223265150bc3bef0be74f55a77c55da88d2f481fccc403ccef26f1f3a09312"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
