name = "Anarchocapitalism Simulator 2021"
author = "GLua"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "185f57081ea9aa7c1c35cfcb9a62ba1635a2332ccc81de4f1152300e38f63cf8"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
