name = "Anarchocapitalism Simulator 2021"
author = "GLua"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92212197a519d847257d9c57ce53e438def668d962ffc4ed90fc04f9cb42f24d"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
