name = "StaTech Industry"
author = "static"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce97469196366438aaf00a5cb5d5a26677d5f3b30cbaf2a5311fe14ab6adc57"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
