name = "StaTech Industry"
author = "static"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2fb7106542081182586a721283fa9c816541238f57381e81e0746e58039a2ff"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
