name = "StaTech Industry"
author = "static"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef6d7cb76115a3e30544da75fc7e33d65629451b6542e0d2dc794a409416e86f"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
